### PR TITLE
Null safety, support for Huawei AppGallery.

### PR DESCRIPTION
**Pull request by deakjahn**
Nothing needed, just metadata change.

### CODE REVIEW

**Review by dhrn — APPROVED** [review]

**Comment by deakjahn** [comment]
Oops, I forgot to do the same to the example inside... :-) Sorry.

**Comment by deakjahn** [comment]
@dhrn I added something else, transparent support for Huawei AppGallery. The user needs nothing to do, it goes to the appropriate store automatically.

The rest are a deprecated widget and a few Kotlin style warnings from the compiler.

**Comment by dhrn** [comment]
Seems @heqingbao  is not going maintain the project. 

@deakjahn are you ok to maintain this project?. If yes let's create fork from this project(include me to that project) and will start contributing to that project. Is that fine?

**Comment by deakjahn** [comment]
Just fine with me if you want to. :-) I have a few others, so I'm not at all determined to have it to my name, it would be just as fine among yours. If we do, there are a few more cosmetic changes that could be done, too.

I'm not a fan of `flutter` always appearing in plugin names but in this case, to differentiate, maybe `flutter_launch_store` or something similar?

**Comment by deakjahn** [comment]
Shall I or you will? I could try to modify the name of my fork to see what happens, I never did anything similar in GitHub. :-)

**Comment by dhrn** [comment]
Hey @deakjahn ,

sorry for late reply. I think let's create a repo and push all the commit. We can add one line in the readme to convey that this fork this repo like that. Is this fine?

**Comment by dhrn** [comment]
May be we can create GitHub organization where we keep our opensource library?

**Pull request closed without merging**
